server:
  port: 8088
spring:
  application:
    name: cart-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
leyou:
  jwt:
    pubKeyPath: C:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: token # cookie的名称